bar/urls.py
from django.urls import path

from bar.views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    GenreListView,
    GenreDetailView,
    GenreUpdateView,
    GenreCreateView,
    GenreDeleteView,
    MusicianListView,
    MusicianDetailView,
    MusicianCreateView,
    MusicianUpdateView,
    MusicianDeleteView,
    RockbandListView,
    RockbandDetailView,
    RockbandCreateView,
    RockbandUpdateView,
    RockbandDeleteView,
    EventListView,
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    VisitorDetailView,
    VisitorCreateView,
    VisitorDeleteView, toggle_assign_to_events, VisitorListView)

urlpatterns = [
    path("", index, name="index"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "genres/",
        GenreListView.as_view(),
        name="genre-list",
    ),
    path(
        "genres/<int:pk>/",
        GenreDetailView.as_view(),
        name="genre-detail",
    ),
    path(
        "genres/create/",
        GenreCreateView.as_view(),
        name="genre-create",
    ),
    path(
        "genres/<int:pk>/update/",
        GenreUpdateView.as_view(),
        name="genre-update",
    ),
    path(
        "genres/<int:pk>/delete/",
        GenreDeleteView.as_view(),
        name="genre-delete",
    ),
    path(
        "musicians/",
        MusicianListView.as_view(),
        name="musician-list",
    ),
    path(
        "musicians/<int:pk>/",
        MusicianDetailView.as_view(),
        name="musician-detail",
    ),
    path(
        "musicians/create/",
        MusicianCreateView.as_view(),
        name="musician-create",
    ),
    path(
        "musicians/<int:pk>/update/",
        MusicianUpdateView.as_view(),
        name="musician-update",
    ),
    path(
        "musicians/<int:pk>/delete/",
        MusicianDeleteView.as_view(),
        name="musician-delete",
    ),
    path(
        "rockbands/",
        RockbandListView.as_view(),
        name="rockband-list",
    ),
    path(
        "rockbands/<int:pk>/",
        RockbandDetailView.as_view(),
        name="rockband-detail",
    ),
    path(
        "rockbands/create/",
        RockbandCreateView.as_view(),
        name="rockband-create",
    ),
    path(
        "rockbands/<int:pk>/update/",
        RockbandUpdateView.as_view(),
        name="rockband-update",
    ),
    path(
        "rockbands/<int:pk>/delete/",
        RockbandDeleteView.as_view(),
        name="rockband-delete",
    ),
    path(
        "events/",
        EventListView.as_view(),
        name="event-list",
    ),
    path(
        "events/<int:pk>/",
        EventDetailView.as_view(),
        name="event-detail",
    ),
    path(
        "events/create/",
        EventCreateView.as_view(),
        name="event-create",
    ),
    path(
        "events/<int:pk>/update/",
        EventUpdateView.as_view(),
        name="event-update",
    ),
    path(
        "events/<int:pk>/delete/",
        EventDeleteView.as_view(),
        name="event-delete",
    ),
    path(
        "events/<int:pk>/toggle-assign/",
        toggle_assign_to_events,
        name="toggle-events-assign",
    ),
    path(
        "visitors/",
        VisitorListView.as_view(),
        name="visitor-list",
    ),
    path(
        "visitors/<int:pk>/",
        VisitorDetailView.as_view(),
        name="visitor-detail",
    ),
    path(
        "visitors/create/",
        VisitorCreateView.as_view(),
        name="visitor-create",
    ),
    path(
        "visitors/<int:pk>/delete/",
        VisitorDeleteView.as_view(),
        name="visitor-delete",
    ),
]

app_name = "bar"

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bar.urls", namespace="bar")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<div class="footer">
    <p>Project by Dmytry Donchyk, 2023</p>
</div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link btn-custom">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link btn-custom">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link btn-custom">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:visitor-detail' pk=user.id %}">{{ user.get_username }}</a></li>
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'logout'%}">Logout</a></li>
    {% else %}
      <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>

    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:visitor-create'%}">Registration</a></li>
    {% endif %}
  <br>
  {% if user.is_authenticated %}
  <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:index' %}">Home</a></li>
  <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:event-list' %}">All events</a></li>
  <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:genre-list' %}">All genres</a></li>
  <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:rockband-list' %}">All bands</a></li>
  <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:musician-list' %}">All musicians</a></li>
  {% if user.is_superuser %}
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:position-list' %}">All positions</a></li>
    <li class="list-group-item block-on-sidebar"><a class="nav-link" href="{% url 'bar:visitor-list' %}">All visitors</a></li>
  {% endif %}
  {% endif %}
</ul>