bar/urls.py
from django.urls import path

from bar.views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    GenreListView,
    GenreDetailView,
    GenreUpdateView,
    GenreCreateView,
    GenreDeleteView,
    MusicianListView,
    MusicianDetailView,
    MusicianCreateView,
    MusicianUpdateView,
    MusicianDeleteView,
    RockbandListView,
    RockbandDetailView,
    RockbandCreateView,
    RockbandUpdateView,
    RockbandDeleteView,
    EventListView,
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    VisitorDetailView,
    VisitorCreateView,
    VisitorDeleteView, toggle_assign_to_events, VisitorListView)

urlpatterns = [
    path("", index, name="index"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "genres/",
        GenreListView.as_view(),
        name="genre-list",
    ),
    path(
        "genres/<int:pk>/",
        GenreDetailView.as_view(),
        name="genre-detail",
    ),
    path(
        "genres/create/",
        GenreCreateView.as_view(),
        name="genre-create",
    ),
    path(
        "genres/<int:pk>/update/",
        GenreUpdateView.as_view(),
        name="genre-update",
    ),
    path(
        "genres/<int:pk>/delete/",
        GenreDeleteView.as_view(),
        name="genre-delete",
    ),
    path(
        "musicians/",
        MusicianListView.as_view(),
        name="musician-list",
    ),
    path(
        "musicians/<int:pk>/",
        MusicianDetailView.as_view(),
        name="musician-detail",
    ),
    path(
        "musicians/create/",
        MusicianCreateView.as_view(),
        name="musician-create",
    ),
    path(
        "musicians/<int:pk>/update/",
        MusicianUpdateView.as_view(),
        name="musician-update",
    ),
    path(
        "musicians/<int:pk>/delete/",
        MusicianDeleteView.as_view(),
        name="musician-delete",
    ),
    path(
        "rockbands/",
        RockbandListView.as_view(),
        name="rockband-list",
    ),
    path(
        "rockbands/<int:pk>/",
        RockbandDetailView.as_view(),
        name="rockband-detail",
    ),
    path(
        "rockbands/create/",
        RockbandCreateView.as_view(),
        name="rockband-create",
    ),
    path(
        "rockbands/<int:pk>/update/",
        RockbandUpdateView.as_view(),
        name="rockband-update",
    ),
    path(
        "rockbands/<int:pk>/delete/",
        RockbandDeleteView.as_view(),
        name="rockband-delete",
    ),
    path(
        "events/",
        EventListView.as_view(),
        name="event-list",
    ),
    path(
        "events/<int:pk>/",
        EventDetailView.as_view(),
        name="event-detail",
    ),
    path(
        "events/create/",
        EventCreateView.as_view(),
        name="event-create",
    ),
    path(
        "events/<int:pk>/update/",
        EventUpdateView.as_view(),
        name="event-update",
    ),
    path(
        "events/<int:pk>/delete/",
        EventDeleteView.as_view(),
        name="event-delete",
    ),
    path(
        "events/<int:pk>/toggle-assign/",
        toggle_assign_to_events,
        name="toggle-events-assign",
    ),
    path(
        "visitors/",
        VisitorListView.as_view(),
        name="visitor-list",
    ),
    path(
        "visitors/<int:pk>/",
        VisitorDetailView.as_view(),
        name="visitor-detail",
    ),
    path(
        "visitors/create/",
        VisitorCreateView.as_view(),
        name="visitor-create",
    ),
    path(
        "visitors/<int:pk>/delete/",
        VisitorDeleteView.as_view(),
        name="visitor-delete",
    ),
]

app_name = "bar"

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bar.urls", namespace="bar")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bar/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


from bar.models import (
    Visitor,
    Rockband,
    Genre,
    Musician,
    Position,
    Event
)


class EventForm(forms.ModelForm):
    visitors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    bands = forms.ModelMultipleChoiceField(
        queryset=Rockband.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Event
        fields = "__all__"


class RockbandForm(forms.ModelForm):

    musicians = forms.ModelMultipleChoiceField(
        queryset=Musician.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Rockband
        fields = "__all__"


class MusicianForm(forms.ModelForm):

    position = forms.ModelMultipleChoiceField(
        queryset=Position.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Musician
        fields = "__all__"


class PositionCreationForm(forms.Form):
    class Meta:
        model = Position
        fields = "__all__"


class GenreCreationForm(forms.Form):
    class Meta:
        model = Genre
        fields = "__all__"


class MusicianCreationForm(forms.Form):
    class Meta:
        model = Musician
        fields = "__all__"


class RockbandCreationForm(forms.Form):
    class Meta:
        model = Rockband
        fields = "__all__"


class VisitorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Visitor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
        )


class EventCreationForm(forms.Form):
    class Meta:
        model = Event
        fields = "__all__"


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by position`s name"
            }
        ),
    )


class GenreSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by genre`s name"
            }
        ),
    )


class MusicianSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by musician`s last name"
            }
        ),
    )


class RockbandSearchForm(forms.Form):
    band_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by band`s name"
            }
        ),
    )


class EventSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by event`s name"
            }
        ),
    )


class VisitorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        ),
    )

bar/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from bar.forms import (
    PositionSearchForm,
    GenreSearchForm,
    MusicianSearchForm,
    RockbandSearchForm,
    EventSearchForm,
    VisitorCreationForm,
    VisitorSearchForm,
    EventForm,
    RockbandForm,
    MusicianForm
)
from bar.models import (
    Genre,
    Event,
    Rockband,
    Position,
    Musician,
    Visitor
)


def index(request: HttpRequest) -> HttpResponse:
    """View function for the home page of this site"""

    num_events = Event.objects.count()
    num_bands = Rockband.objects.count()
    num_musicians = Musician.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_events": num_events,
        "num_bands": num_bands,
        "num_musicians": num_musicians,
        "num_visits": num_visits + 1,
    }

    return render(request, "bar/index.html", context=context)


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = PositionSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("bar:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("bar:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("bar:position-list")


class GenreListView(LoginRequiredMixin, generic.ListView):
    model = Genre
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GenreListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = GenreSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Genre.objects.all()
        form = GenreSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class GenreDetailView(LoginRequiredMixin, generic.DetailView):
    model = Genre


class GenreCreateView(LoginRequiredMixin, generic.CreateView):
    model = Genre
    fields = "__all__"
    success_url = reverse_lazy("bar:genre-list")


class GenreUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Genre
    fields = "__all__"
    success_url = reverse_lazy("bar:genre-list")


class GenreDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Genre
    success_url = reverse_lazy("bar:genre-list")


class MusicianListView(LoginRequiredMixin, generic.ListView):
    model = Musician
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MusicianListView, self).get_context_data(**kwargs)

        last_name = self.request.GET.get("last_name", "")

        context["search_form"] = MusicianSearchForm(initial={
            "last_name": last_name
        })

        return context

    def get_queryset(self):
        queryset = Musician.objects.all()
        form = MusicianSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                last_name__icontains=form.cleaned_data["last_name"]
            )

        return queryset


class MusicianDetailView(LoginRequiredMixin, generic.DetailView):
    model = Musician


class MusicianCreateView(LoginRequiredMixin, generic.CreateView):
    model = Musician
    form_class = MusicianForm
    success_url = reverse_lazy("bar:musician-list")


class MusicianUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Musician
    form_class = MusicianForm
    success_url = reverse_lazy("bar:musician-list")


class MusicianDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Musician
    success_url = reverse_lazy("bar:musician-list")


class RockbandListView(LoginRequiredMixin, generic.ListView):
    model = Rockband
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RockbandListView, self).get_context_data(**kwargs)

        band_name = self.request.GET.get("band_name", "")

        context["search_form"] = RockbandSearchForm(initial={
            "band_name": band_name
        })

        return context

    def get_queryset(self):
        queryset = Rockband.objects.all()
        form = RockbandSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                band_name__icontains=form.cleaned_data["band_name"]
            )

        return queryset


class RockbandDetailView(LoginRequiredMixin, generic.DetailView):
    model = Rockband


class RockbandCreateView(LoginRequiredMixin, generic.CreateView):
    model = Rockband
    form_class = RockbandForm
    success_url = reverse_lazy("bar:rockband-list")


class RockbandUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Rockband
    form_class = RockbandForm
    success_url = reverse_lazy("bar:rockband-list")


class RockbandDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Rockband
    success_url = reverse_lazy("bar:rockband-list")


class VisitorListView(LoginRequiredMixin, generic.ListView):
    model = Visitor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VisitorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = VisitorSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        queryset = Visitor.objects.all()
        form = VisitorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class VisitorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Visitor
    queryset = Visitor.objects.prefetch_related("events__visitors")


class VisitorCreateView(generic.CreateView):
    model = Visitor
    form_class = VisitorCreationForm
    success_url = reverse_lazy("bar:event-list")


class VisitorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Visitor
    fields = "__all__"
    success_url = reverse_lazy("bar:index")


class VisitorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Visitor
    success_url = reverse_lazy("bar:index")


class EventListView(LoginRequiredMixin, generic.ListView):
    model = Event
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = EventSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Event.objects.all()
        form = EventSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class EventDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event


class EventCreateView(LoginRequiredMixin, generic.CreateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("bar:event-list")


class EventUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("bar:event-list")


class EventDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Event
    success_url = reverse_lazy("bar:event-list")


@login_required
def toggle_assign_to_events(request, pk):
    visitor = Visitor.objects.get(id=request.user.id)
    if (
        Event.objects.get(id=pk) in visitor.events.all()
    ):
        visitor.events.remove(pk)
    else:
        visitor.events.add(pk)
    return HttpResponseRedirect(reverse_lazy("bar:event-list"))

templates/bar/event_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this event?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/event_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="section-name">
    <p>Title: </p>
  </div>
  <h2>
  "{{ event.name }}"
  </h2>
  <div class="section-name">
    Bands which take part in this event:
  </div>
    <ul>
      {% for band in event.bands.all %}
        <li>
          <a class="list-link-style" href="{% url 'bar:rockband-detail' pk=band.id %}">
            {{ band.band_name }}
          </a>
        </li>
      {% endfor %}
    </ul>
  <hr>
  <div class="section-name">
    Show time:
  </div>
  <div class="description-style">
    <p>  {{ event.show_time }}</p>
  </div>
  <div class="section-name">
    Ticket cost:
  </div>
  <div class="description-style">
    <p>{{ event.ticket_cost }}</p>
  </div>>
  {% if event in user.events.all %}
      <a href="{% url 'bar:toggle-events-assign' pk=event.id %}" class="btn btn-danger btn-reverse link-to-page">
        I don't want to go!
      </a>
    {% else %}
      <a href="{% url 'bar:toggle-events-assign' pk=event.id %}" class="btn btn-success btn-custom link-to-page">
        I want to go!
      </a>
    {% endif %}
  {% if user.is_superuser %}
  <a href="{% url 'bar:event-delete' pk=event.id %}" class="btn btn-danger btn-reverse link-to-page">
    Delete
  </a>
  <a href="{% url 'bar:event-update' pk=event.id %}" class="btn btn-secondary btn-reverse link-to-page">
    Update
  </a>
  {% endif %}
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary btn-custom link-to-page">Return</a>
{% endblock %}

templates/bar/event_list.html
{% extends "base.html" %}


{% block content %}
  <h1>
    Events List
    {% if user.is_superuser %}
    <a href="{% url 'bar:event-create' %}" class="btn btn-primary btn-custom link-to-page">
      Create
    </a>
    {% endif %}
  </h1>

  <form action="" method="get" class="form-inline">
    <div>
      {{ search_form.as_p }}
      <input type="submit" class="btn btn-secondary btn-custom" value="Search">
    </div>
  </form>

  {% if event_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name:</th>
      </tr>

      {% for event in event_list %}
        <tr>
          <td>
              {{ event.id }}
          </td>
          <td>
            <a class="list-link-style" href="{% url "bar:event-detail" pk=event.id %} ">
              {{ event.name }}
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no events!</p>
  {% endif %}
{% endblock %}

templates/bar/genre_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="section-name">
    <p>{{ genre.name }}</p>
  </div>
  <article class="description-style">
    <p>Description: {{ genre.description }}</p>
  </article>
  <div class="section-name">
    <p>Bands in Starry, which plays this genre:</p>
  </div>
  <hr>
  <ul>
    {% for rockband in genre.rockbands.all %}
      <li>
        <a class="nav-link" href="{% url 'bar:rockband-detail' pk=rockband.id %}" >
          {{ rockband.band_name }}
        </a>
      </li>
    {% empty %}
      <div class="description-style">
        <p>No bands who play this type of music for now in Starry's schedule!</p>
      </div>
    {% endfor %}
  </ul>
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary btn-custom">Return</a>
{% endblock %}

templates/bar/genre_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} genre</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-reverse ">Cancel</a>
  </form>
{% endblock %}

templates/bar/musician_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this musician?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/position_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/position_list.html
{% extends "base.html" %}


{% block content %}
  <h1>
    Positions List
    <a href="{% url 'bar:position-create' %}" class="btn btn-primary btn-custom link-to-page">
      Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    <div>
      {{ search_form.as_p }}
      <input type="submit" class="btn btn-secondary btn-custom" value="Search">
    </div>
  </form>

  {% if position_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th style="color: yellow">Delete</th>
      </tr>

      {% for position in position_list %}
        <tr>
          <td>
              {{ position.id }}
          </td>
          <td>
              {{ position.name }}
          </td>
          <td>
              <a class="list-link-style" href="{% url 'bar:position-update' pk=position.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: yellow"
                href="{% url 'bar:position-delete' pk=position.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no positions!</p>
  {% endif %}
{% endblock %}

templates/bar/rockband_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="section-name">
    <p>Band name: </p>
  </div>
  <h2>
  {{ rockband.band_name }}
  </h2>
  <div class="section-name">
    <p>Musicians that playing in this band: </p>
  </div>
  <div class="container-home-page">
    <div class="container-home-page">
      {% for musician in rockband.musicians.all %}
        <div class="front-block">
          <a class="nav-link" href="{% url "bar:musician-detail" pk=musician.id %} ">
            {{ musician.first_name }} {{ musician.last_name }}
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="section-name">
    Genre that this band represents:
  </div>
    <a class="nav-link" href="{% url "bar:genre-detail" pk=rockband.genres.id %} ">
    {{ rockband.genres.name }}
    </a>
  <hr>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary btn-custom">Return</a>
{% endblock %}

templates/bar/rockband_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} band:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/visitor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this visitor?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/visitor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="section-name">
    <p>Private cabinet: </p>
  </div>

  <article>
    <h2>
    Username: {{ visitor.username }}
      <a href="{% url 'bar:visitor-delete' pk=visitor.id %}" class="btn btn-danger btn-reverse link-to-page">
        Delete
      </a>
    </h2>
    <p><strong>First name:</strong> {{ visitor.first_name }}</p>
    <p><strong>Last name:</strong> {{ visitor.last_name }}</p>
  </article>


  <div class="ml-3">
    <h4 class="description-style">Events, you want to visit:</h4>

    {% for event in visitor.events.all %}
      <hr>
        <p>
          <strong>Event:</strong>
          <a class="description-style" href="{% url 'bar:event-detail' pk=event.id %}">
            {{ event.name }}
          </a>
        </p>
    {% empty %}
      <p>No events!</p>
    {% endfor %}
  </div>
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary btn-custom">Return</a>
{% endblock %}

templates/bar/visitor_form.html
{% extends "base.html" %}

{% block content %}
  <h1>Create visitor</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary btn-custom">
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-reverse">Cancel</a>
  </form>
{% endblock %}

templates/bar/visitor_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      Visitors List
      <a href="{% url 'bar:visitor-create' %}" class="btn btn-primary btn-custom link-to-page">
        Create
      </a>
    </h1>

    <form action="" method="get" class="form-inline">
      <div>
        {{ search_form.as_p }}
        <input type="submit" class="btn btn-secondary btn-custom" value="Search">
      </div>
    </form>

    {% if visitor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th style="color: firebrick">Last name</th>
      </tr>
    {% for visitor in visitor_list %}
      <tr>
        <td>{{ visitor.id }}</td>
        <td>
          <a class="list-link-style" href="{% url "bar:visitor-detail" pk=visitor.id %}">
            {{ visitor.username }}
            {% if user == visitor %}
              (Me)
            {% endif %}
          </a>
        </td>
        <td>{{ visitor.first_name }}</td>
        <td style="color: firebrick">{{ visitor.last_name }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no visitors in the Starry music-bar for now.</p>
    {% endif %}
{% endblock %}